### ISSUE TITLE
mevboost v1.5.0: GLIBC_2.32 not found 

### ISSUE THREAD

**Issue by PanosChtz** [flashbots/mev-boost#469]
Upgraded from 1.4.0 to 1.5.0 and I'm getting the error:

```
Mar 14 12:59:30 validator mev-boost[1053665]: /usr/local/bin/mev-boost: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/mev-boost)
```

Running Ubuntu 20.04 LTS on RPi4.
Reverted back to v.1.4.0 which runs fine.
Any solution?

**Comment by Jor-Tech** [comment]
Getting same on Linux-amd64 system with ubuntu 20.04.5 LTS:

```
mev-boost: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by mev-boost)
mev-boost: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by mev-boost)
```

**Comment by PerfectDark99** [comment]
Same for me on Ubuntu 20.04 LTS. This ships with glibc_2.31.
updating that is a pretty big can of worms and the fact it seems to need 2.32 and 2.34 is even more confusing / limiting. likely would mean installing 2 versions into you home dir. eg big no no and this released should be fixed ASAP.

**Comment by matthewmarcus** [comment]
Getting same error.

Noticed 1.50 release notes state: "This release may not work with Ubuntu 20.04 LTS and require an upgrade to Ubuntu 22.04 LTS."

IMO, this is unacceptable. Forcing users to upgrade their OS for a new release is also a big no no.

**Comment by Jor-Tech** [comment]
Manual compile worked for me and might be a temporary solution for others who read this and like to upgrade.

Still I think pre build versions should also be compatible with Ubuntu 20.04 LTS and not force you to upgrade distro. Especially when running LTS.

**Comment by PanosChtz** [comment]
@Jor-Tech what is the platform you compiled on?

Agree this shouldn't be a forced distro upgrade for LTS. Hope devs fix this soon.

In the meantime, are we good with 1.4.0? Or is there a risk of missed proposal?

**Comment by stephane303** [comment]
I have the same issue, running Debian 11, tried to build locally, but that didn't solve the problem

**Comment by Jor-Tech** [comment]
> @Jor-Tech what is the platform you compiled on?
> 

Build locally on my node which is a Linux-amd64 system running ubuntu 20.04.5 LTS.

**Comment by remyroy** [comment]
Detailed instructions on how to locally build this on Ubuntu 20.04 and solve this issue can be found on https://www.reddit.com/r/ethstaker/comments/11re3nd/comment/jcacoq8/

**Comment by matthewmarcus** [comment]
> 

This worked for me. Thanks @remyroy!

**Comment by PanosChtz** [comment]
Confirmed local build worked for me as well. Hope devs release binaries that work without the need to local build or to upgrade from 20.04 LTS (which I assume most validators are still running).

**Comment by Jor-Tech** [comment]
@metachris Thank you very much for addressing this issue and fixing the build in this way!

**Comment by a7e8** [comment]
@metachris can you do the same for arm64? Thanks

**Comment by metachris** [comment]
I made a new pre-release v1.5.1-alpha1 that has the statically built arm images attached: https://github.com/flashbots/mev-boost/releases/tag/v1.5.1-alpha1 -- you can download the arm binary from there!

(encountered some cross-compile issues before, and don't have enough time to manually update the arm binary for 1.5.0)

**Comment by metachris** [comment]
Leaving this issue open for a few days for visibility, will close sometime early next week.

**Comment by PanosChtz** [comment]
@metachris I can open make a new PR and add the arm64 binary I compiled, please let me know, thanks
